repos:
  # - repo: https://github.com/ambv/black
  #   rev: 20.8b1
  #   hooks:
  #     - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #     - id: isort
  #       name: isort (cython)
  #       types: [cython]
  #     - id: isort
  #       name: isort (pyi)
  #       types: [pyi]
  - repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: [-v, -i, --fail-under=80]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
