name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: Silleellie/pylint-github-action@v1
      with:
        package-path: ./src/mongopy        
        python-version: ${{ matrix.python-version }}
        requirements-path: requirements.txt
        readme-path: README.md
